// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact         = require("reason-react/lib/js/src/reasonReact.js");
var ReactNativeElements = require("react-native-elements");

function make(buttonStyle, title, backgroundColor, onPress, children) {
  return ReasonReact.wrapJsForReason(ReactNativeElements.Button, {
              buttonStyle: buttonStyle,
              title: title,
              backgroundColor: backgroundColor,
              onPress: onPress
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
